# services:
#   pgdatabase:
#     image: postgres:13
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=root
#       - POSTGRES_DB=ny_taxi
#     volumes:
#       - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
#     ports:
#       - "5432:5432"
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=root
#     ports:
#       - "8080:80"
# networks:
#   pg-network:
#     external: true  # Assuming the pg-network is created elsewhere

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network

networks:
  pg-network:
    external: true  # Assuming the pg-network is created elsewhere

# services:
#   postgres:
#     image: postgres:15
#     environment:
#       - POSTGRES_USER=airflow
#       - POSTGRES_PASSWORD=airflow
#       - POSTGRE_DB=airflow
#     volumes:
#       - postgres-db-volume:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD", "pg_isready", "U", "airflow"]
#       interval: 5s
#       retried: 5
#     restart: always




# docker run -it \
#   -e POSTGRES_USER= "root" \
#   -e POSTGRES_PASSWORD= "root" \
#   -e POSTGRES_DB= "ny_taxi" \
#   -v c:/Users/HP/Desktop/DE Zoomcamp/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
#   -p 5432:5432 \
#   postgres:13



#To run pdagmin in docker

# ####### 1 create docker networks:
#   docker network create pg-network

# ####### 2 connect the database to the network
# docker run -it \
#   -e POSTGRES_USER= "root" \
#   -e POSTGRES_PASSWORD= "root" \
#   -e POSTGRES_DB= "ny_taxi" \
#   -v c:/Users/HP/Desktop/DE Zoomcamp/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
#   -p 5432:5432 \
#   --network=pg-network \
#   --name=pg-database \
#   postgres:13


# docker run -it \
#   -e PGADMIN_DEFAULT_EMAIL=admin@admin.com \
#   -e PGADMIN_DEFAULT_PASSWORD=root \
#   -p "8080:80 \
#   dpage/pgadmin4